os: Visual Studio 2015

install:
  - choco install --x86 nodejs.install 
  - "\"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat\" x86"
  - mkdir .\\third_party
  - mkdir .\\third_party\\webrtc
  - ps: Invoke-WebRequest -Uri https://github.com/FAForever/libwebrtc/releases/download/v1.0.0-faf/libwebrtc-1.0.0-faf-win-x86.zip -OutFile ".\\third_party\\webrtc\\libwebrtc.zip"
  - cd .\\third_party\\webrtc
  - "\"C:\\Program Files\\7-Zip\\7z.exe\" x libwebrtc.zip"
  - cd ..\\..
  - npm install --build-from-source
  - mkdir .\\node-webrtc
  - copy .\\build\\Release\\wrtc.node .\\node-webrtc
  - "copy \"C:\\Program Files (x86)\\nodejs\\node.exe\" .\\node-webrtc"
  - "\"C:\\Program Files\\7-Zip\\7z.exe\" a node-webrtc-win32.zip node-webrtc\\"

artifacts:
  - path: 'node-webrtc-win32.zip'
    name: wrtc_node_archive

deploy:
  - provider: GitHub
    auth_token:
      secure: "+Iy9FWEu+rsOymVlUWI8lRdJZRvjOQpOCuEmA2fjHACAzQxrzas9JQi86RUAPj5K"
    artifact: wrtc_node_archive
    force_update: true
      
build: OFF
test: OFF
